/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import java.awt.Color;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author noman
 */
public class admin1 extends javax.swing.JFrame {
   

    /**
     * Creates new form delete
     */

    public admin1() {
        setVisible(true);
        setTitle("Deleting page");
        getContentPane().setBackground(Color.CYAN);
        initComponents();
           Fillcombo();
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
    }
 private void Fillcombo()
{
    try
    {
        String url="jdbc:mysql://localhost:3306/student";
        String user="root";
        String pass="";
       Connection conn=(Connection)DriverManager.getConnection(url,user,pass);
       String query1= "select * from reg1";
   
                 PreparedStatement preparedStmt = conn.prepareStatement(query1);
                preparedStmt.execute();
                 ResultSet rs1 = preparedStmt.getResultSet();
                 
                 String query2= " select * from book ";
                 PreparedStatement preparedStmt2 = conn.prepareStatement(query2);
                 preparedStmt2.execute();
                 ResultSet rs2 = preparedStmt2.getResultSet();
                 
                 String query3= " select * from book_issue ";
                 PreparedStatement preparedStmt3 = conn.prepareStatement(query3);
                 preparedStmt3.execute();
                 ResultSet rs3 = preparedStmt3.getResultSet();
                      while(rs1.next())
                      {
                   
                   
                   String name=rs1.getString("name");
                   com_name.addItem(name);
                   
                      
                      }
                       while(rs2.next())
                      {
                  String b_name=rs2.getString("book_name");
                 //int id =Integer.parseInt(b_name);
                   com_book.addItem(b_name);
                      
                      }
                        while(rs3.next())
                      {
                  String c_name=rs3.getString("date");
                 //int id =Integer.parseInt(b_name);
                   com_fromb.addItem(c_name);
                      
                      }
                    
                   conn.close();
    }
    catch(SQLException | HeadlessException e)
    {
       System.out.println(e);
    }
   
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l_user = new javax.swing.JLabel();
        com_name = new javax.swing.JComboBox();
        bt_user = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        l_book = new javax.swing.JLabel();
        com_book = new javax.swing.JComboBox();
        bt_book = new javax.swing.JButton();
        l5 = new javax.swing.JLabel();
        l6_book = new javax.swing.JLabel();
        com_fromb = new javax.swing.JComboBox();
        bt_fromb = new javax.swing.JButton();
        bt_back1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 51, 255));
        l1.setText("                       !!! This Page Is For Delete !!!");

        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(0, 51, 255));
        l2.setText("For Deleting User :");

        l_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_user.setForeground(new java.awt.Color(0, 51, 255));
        l_user.setText("Select User Name");

        com_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        com_name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Username" }));
        com_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_nameActionPerformed(evt);
            }
        });

        bt_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_user.setForeground(new java.awt.Color(255, 0, 51));
        bt_user.setText("Delete");
        bt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_userActionPerformed(evt);
            }
        });

        l3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(0, 51, 255));
        l3.setText("For Deleting from Book :");

        l_book.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_book.setForeground(new java.awt.Color(0, 51, 204));
        l_book.setText("Select Book Name");

        com_book.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        com_book.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bookname" }));
        com_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_bookActionPerformed(evt);
            }
        });

        bt_book.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_book.setForeground(new java.awt.Color(255, 0, 51));
        bt_book.setText("Delete!");
        bt_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bookActionPerformed(evt);
            }
        });

        l5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l5.setForeground(new java.awt.Color(0, 51, 204));
        l5.setText("For Deleting From  Book_issue");

        l6_book.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l6_book.setForeground(new java.awt.Color(0, 51, 204));
        l6_book.setText("Select Date");

        com_fromb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        com_fromb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));

        bt_fromb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_fromb.setForeground(new java.awt.Color(204, 0, 51));
        bt_fromb.setText("Delete!!");
        bt_fromb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_frombActionPerformed(evt);
            }
        });

        bt_back1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_back1.setForeground(new java.awt.Color(0, 204, 153));
        bt_back1.setText("Back");
        bt_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_back1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(l6_book, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(com_fromb, 0, 106, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(l_user, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                            .addComponent(l_book, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(com_name, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(com_book, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(l3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_fromb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(bt_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_user, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_user))
                .addGap(31, 31, 31)
                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_book, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_book))
                .addGap(32, 32, 32)
                .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l6_book, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_fromb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_fromb))
                .addGap(18, 18, 18)
                .addComponent(bt_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_userActionPerformed
        // TODO add your handling code here:
       int d = JOptionPane.showConfirmDialog(null,"Do you Really want to Delete","Delete",JOptionPane.YES_NO_OPTION);
        if(d==0)
        {

       try
    {
        String s_name = com_name.getSelectedItem().toString(); 
        String url="jdbc:mysql://localhost:3306/student";
        String user="root";
        String pass="";
        Connection conn=(Connection)DriverManager.getConnection(url,user,pass);
        String query1="delete   from reg1 where name='"+ s_name +"' "; //for student
       
         
         //String query2="delete  from book where book_name='"+ b_name +"' "; //for book
        
          //JOptionPane.showMessageDialog(null,"are you sure??? you want to delete the name !!");
         PreparedStatement preparedStmt = conn.prepareStatement(query1);
              
         //ResultSet rs1 = preparedStmt.getResultSet();
         preparedStmt.execute();
          
     
    conn.close(); 
    }
      
      
       
    
     catch(SQLException | HeadlessException fe)
    {
    
     System.err.println("Got an exception in delete!");
    }
        }
    }//GEN-LAST:event_bt_userActionPerformed

    private void bt_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bookActionPerformed
        // TODO add your handling code here:
        int d = JOptionPane.showConfirmDialog(null,"Do you Really want to Delete","Delete",JOptionPane.YES_NO_OPTION);
        if(d==0)
        {

         try
    {
      
        String c_name = com_book.getSelectedItem().toString();
        //int b_id =Integer.parseInt(c_name);

        
        String url="jdbc:mysql://localhost:3306/student";
        String user="root";
        String pass="";
        Connection conn=(Connection)DriverManager.getConnection(url,user,pass);
        //String query1="delete   from reg1 where name='"+ s_name +"' "; //for student
       
          //JOptionPane.showMessageDialog(null,"are you sure??? you want to delete the book !!");
         String query2=" delete  from book where book_name= '"+ c_name +"' " ; //for book
        
         PreparedStatement preparedStmt2 = conn.prepareStatement(query2);
              
         //ResultSet rs1 = preparedStmt.getResultSet();
         preparedStmt2.execute();
        
          
        conn.close(); 
    }
         
     catch(SQLException | HeadlessException ne)
    {
    
     System.err.println("Got an exception in delete!");
    }
        }
         
    }//GEN-LAST:event_bt_bookActionPerformed

    private void com_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_nameActionPerformed
        // TODO add your handling code here:
 
   
    }//GEN-LAST:event_com_nameActionPerformed

    private void com_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_bookActionPerformed
        // TODO add your handling code here:

   
    }//GEN-LAST:event_com_bookActionPerformed

    private void bt_frombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_frombActionPerformed
        // TODO add your handling code here:
        int d = JOptionPane.showConfirmDialog(null,"Do you Really want to Delete","Delete",JOptionPane.YES_NO_OPTION);
        if(d==0)
        {

           try
    {
        String d_name = com_fromb.getSelectedItem().toString();
       // int d_id =Integer.parseInt(d_name);
        String url="jdbc:mysql://localhost:3306/student";
        String user="root";
        String pass="";
        Connection conn=(Connection)DriverManager.getConnection(url,user,pass);
        String query1="delete   from book_issue where date='"+ d_name +"' "; //for student
       
         
         //String query2="delete  from book where book_name='"+ b_name +"' "; //for book
        
         //JOptionPane.showMessageDialog(null,"are you sure??? you want to delete the date !!");
         PreparedStatement preparedStmt = conn.prepareStatement(query1);
              
         //ResultSet rs1 = preparedStmt.getResultSet();
         preparedStmt.execute();
         
          
     
    conn.close(); 
    }
      
      
       
    
     catch(SQLException | HeadlessException fe)
    {
    
     System.err.println("Got an exception in delete!");
    }  
        }
        
    }//GEN-LAST:event_bt_frombActionPerformed

    private void bt_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_back1ActionPerformed
        // TODO add your handling code here:
       setVisible(false);
    }//GEN-LAST:event_bt_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new admin1().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back1;
    private javax.swing.JButton bt_book;
    private javax.swing.JButton bt_fromb;
    private javax.swing.JButton bt_user;
    private javax.swing.JComboBox com_book;
    private javax.swing.JComboBox com_fromb;
    private javax.swing.JComboBox com_name;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6_book;
    private javax.swing.JLabel l_book;
    private javax.swing.JLabel l_user;
    // End of variables declaration//GEN-END:variables


     
}

