/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Color;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * @author noman
 */
public class query_search extends javax.swing.JFrame {

    /**
     * Creates new form query_search
     */
    public query_search() {
        initComponents();
          setTitle("Search Page For Users");
      getContentPane().setBackground(Color.CYAN);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l_q1 = new javax.swing.JLabel();
        bt_q1 = new javax.swing.JButton();
        l_q2 = new javax.swing.JLabel();
        bt_q2 = new javax.swing.JButton();
        l_q3 = new javax.swing.JLabel();
        bt_q3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_q4 = new javax.swing.JButton();
        l_q5 = new javax.swing.JLabel();
        bt_q5 = new javax.swing.JButton();
        l_q6 = new javax.swing.JLabel();
        bt_q6 = new javax.swing.JButton();
        l_q7 = new javax.swing.JLabel();
        bt_q7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bt_q8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 51, 51));
        l1.setText("                                     Query Implementation  Page");

        l_q1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_q1.setForeground(new java.awt.Color(0, 51, 204));
        l_q1.setText("Number of books of same type");

        bt_q1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_q1.setForeground(new java.awt.Color(0, 153, 153));
        bt_q1.setText("Query1");
        bt_q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_q1ActionPerformed(evt);
            }
        });

        l_q2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_q2.setForeground(new java.awt.Color(0, 51, 204));
        l_q2.setText("Students   who  didn’t  issue  any  book");

        bt_q2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_q2.setForeground(new java.awt.Color(0, 153, 153));
        bt_q2.setText("Query2");
        bt_q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_q2ActionPerformed(evt);
            }
        });

        l_q3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_q3.setForeground(new java.awt.Color(0, 51, 204));
        l_q3.setText("Available  story  books  by  “Humayun   Ahmed ”");

        bt_q3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_q3.setForeground(new java.awt.Color(0, 153, 153));
        bt_q3.setText("Query3");
        bt_q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_q3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Students  who  have  issued  book   “ Himu ”");

        bt_q4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_q4.setForeground(new java.awt.Color(0, 153, 153));
        bt_q4.setText("Query4");
        bt_q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_q4ActionPerformed(evt);
            }
        });

        l_q5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_q5.setForeground(new java.awt.Color(0, 51, 153));
        l_q5.setText("Books issued in a certain date range");

        bt_q5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_q5.setForeground(new java.awt.Color(0, 153, 153));
        bt_q5.setText("Query5");
        bt_q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_q5ActionPerformed(evt);
            }
        });

        l_q6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_q6.setForeground(new java.awt.Color(0, 51, 153));
        l_q6.setText("student who issued more than 1(one) book ");

        bt_q6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_q6.setForeground(new java.awt.Color(0, 153, 153));
        bt_q6.setText("Query6");
        bt_q6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_q6ActionPerformed(evt);
            }
        });

        l_q7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_q7.setForeground(new java.awt.Color(0, 51, 153));
        l_q7.setText("Categorization  of  students  according  to  issue  book");

        bt_q7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_q7.setForeground(new java.awt.Color(0, 153, 153));
        bt_q7.setText("Query7");
        bt_q7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_q7ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Name all Books written by some author who has written 'Himu'");

        bt_q8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_q8.setForeground(new java.awt.Color(0, 153, 153));
        bt_q8.setText("Query8");
        bt_q8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_q8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_q5, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l_q3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                                .addComponent(l_q2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l_q1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_q7, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_q6, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_q2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_q3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_q4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_q5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_q6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_q7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_q8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_q4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_q1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_q1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_q2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_q3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_q3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_q5)
                    .addComponent(l_q5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_q6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_q6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_q7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_q7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_q8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_q1ActionPerformed
        // TODO add your handling code here:
         query_report1 a = new query_report1();
          a.setVisible(true);   
    }//GEN-LAST:event_bt_q1ActionPerformed

    private void bt_q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_q2ActionPerformed
        // TODO add your handling code here:
        Book_search4 a = new Book_search4();
          a.setVisible(true);   
    }//GEN-LAST:event_bt_q2ActionPerformed

    private void bt_q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_q3ActionPerformed
        // TODO add your handling code here:
        query_report3 a = new query_report3();
          a.setVisible(true);   
    }//GEN-LAST:event_bt_q3ActionPerformed

    private void bt_q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_q4ActionPerformed
        // TODO add your handling code here:
         query_report4 a = new query_report4();
          a.setVisible(true);   
    }//GEN-LAST:event_bt_q4ActionPerformed

    private void bt_q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_q5ActionPerformed
        // TODO add your handling code here:
         query_report5 a = new query_report5();
          a.setVisible(true);   
    }//GEN-LAST:event_bt_q5ActionPerformed

    private void bt_q6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_q6ActionPerformed
        // TODO add your handling code here:
         query_report6 a = new query_report6();
          a.setVisible(true);   
    }//GEN-LAST:event_bt_q6ActionPerformed

    private void bt_q7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_q7ActionPerformed
        // TODO add your handling code here:
         query_report7 a = new query_report7();
          a.setVisible(true);   
    }//GEN-LAST:event_bt_q7ActionPerformed

    private void bt_q8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_q8ActionPerformed
        // TODO add your handling code here:
         query_report8 a = new query_report8();
          a.setVisible(true);   
    }//GEN-LAST:event_bt_q8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(query_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(query_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(query_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(query_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new query_search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_q1;
    private javax.swing.JButton bt_q2;
    private javax.swing.JButton bt_q3;
    private javax.swing.JButton bt_q4;
    private javax.swing.JButton bt_q5;
    private javax.swing.JButton bt_q6;
    private javax.swing.JButton bt_q7;
    private javax.swing.JButton bt_q8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l_q1;
    private javax.swing.JLabel l_q2;
    private javax.swing.JLabel l_q3;
    private javax.swing.JLabel l_q5;
    private javax.swing.JLabel l_q6;
    private javax.swing.JLabel l_q7;
    // End of variables declaration//GEN-END:variables
}
